# Q. 1      A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units. A randomly selected sample of cutlets was collected from both units and measured? Analyze the data and draw inferences at 5% significance level. Please state the assumptions and tests that you carried out to check validity of the assumptions.

In [1]:
import pandas as pd
import scipy 
import numpy as np
from scipy import stats

In [3]:
df = pd.read_csv("Cutlets.csv")
df.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [5]:
UnitA = pd.Series(df.iloc[:,0])
UnitA

0     6.8090
1     6.4376
2     6.9157
3     7.3012
4     7.4488
5     7.3871
6     6.8755
7     7.0621
8     6.6840
9     6.8236
10    7.3930
11    7.5169
12    6.9246
13    6.9256
14    6.5797
15    6.8394
16    6.5970
17    7.2705
18    7.2828
19    7.3495
20    6.9438
21    7.1560
22    6.5341
23    7.2854
24    6.9952
25    6.8568
26    7.2163
27    6.6801
28    6.9431
29    7.0852
30    6.7794
31    7.2783
32    7.1561
33    7.3943
34    6.9405
Name: Unit A, dtype: float64

In [6]:
UnitB = pd.Series(df.iloc[:,1])
UnitB

0     6.7703
1     7.5093
2     6.7300
3     6.7878
4     7.1522
5     6.8110
6     7.2212
7     6.6606
8     7.2402
9     7.0503
10    6.8810
11    7.4059
12    6.7652
13    6.0380
14    7.1581
15    7.0240
16    6.6672
17    7.4314
18    7.3070
19    6.7478
20    6.8889
21    7.4220
22    6.5217
23    7.1688
24    6.7594
25    6.9399
26    7.0133
27    6.9182
28    6.3346
29    7.5459
30    7.0992
31    7.1180
32    6.6965
33    6.5780
34    7.3875
Name: Unit B, dtype: float64

In [9]:
# Select Hypothesis:
# Null hypothsis: H0: mu1 = mu2
# Alternative hypothsis: H1: mu1 != mu2

In [10]:
# Significance 5%
# alpha = 0.05
# As it is two tail test so
# alpha_value = alpha/2 = 0.025

In [13]:
# 2-sample 2-tail t test:
p_value = stats.ttest_ind(UnitA,UnitB)
p_value

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

In [14]:
p_value[1]

0.4722394724599501

# Conclusion

In [12]:
# Since p_value is greater than alpha_value, 
#so we fail to reject the null hypothesis. 
#So there is no significant difference between the two samples. 

# Q. 2 TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms. Any error in order form renders it defective and has to be reworked before processing.  The manager wants to check whether the defective %  varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences.

In [21]:
df = pd.read_csv("LabTAT.csv")
df.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

# We are going to conduct Anova to test whether the mean of any of these samples are different or the same.

In [18]:
# Select Hypothesis:
# Null hypothsis: H0: mu1 = mu2 = mu3 = mu4
# Alternative hypothsis: H1: Atleast one of them is different.

In [19]:
# Significance 5%
# alpha = 0.05

In [22]:
p_value = stats.f_oneway(df.iloc[:,0],df.iloc[:,1],df.iloc[:,2],df.iloc[:,3])
p_value

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [23]:
p_value[1]

2.1156708949992414e-57

# Conclusion

In [24]:
# Since p_value is less than alpha_value, 
#so we reject the null hypothesis. 
#So there is significant difference between the two samples.

# Q. 3       Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions.


In [50]:
df = pd.read_csv("BuyerRatio.csv")
df

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [53]:
df1=df.drop("Observed Values",axis=1)

In [54]:
df1

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

# We are going to to conduct Chi - Square test. We need to check whether the proportion of any of these samples are different or the same?

In [27]:
# Select Hypothesis:
# Null hypothsis: H0:  All proportions are equal
# Alternative hypothsis: Not all proportions are equal

In [28]:
# Significance 5%
# alpha = 0.05

Applying Chi-Square contingency table to convert observed value into expected value

In [56]:
stat, p, dof, exp = stats.chi2_contingency(df1) 
print(stat,"\n", p,"\n", dof,"\n", exp)

1.595945538661058 
 0.6603094907091882 
 3 
 [[  42.76531299  146.81287862  131.11756787   72.30424052]
 [ 442.23468701 1518.18712138 1355.88243213  747.69575948]]


In [59]:
observed = np.array([50, 142, 131, 70, 435, 1523, 1356, 750])
expected = np.array([42.76531299,  146.81287862,  131.11756787, 72.30424052, 442.23468701, 1518.18712138, 1355.88243213, 747.69575948])

In [60]:
statistics, p_value = stats.chisquare(observed, expected, ddof = 3)
print("Statistics = ",statistics,"\n",'P_Value = ', p_value)

Statistics =  1.5959455390914483 
 P_Value =  0.8095206646905712


# Conclusion

In [61]:
# Since p_value is greater than alpha_value, 
#so we fail to reject the null hypothesis. 
#So there is no dependency between male and femal buyers rations and are similar across regions.

# Q. 4      TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms. Any error in order form renders it defective and has to be reworked before processing.  The manager wants to check whether the defective %  varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences.

In [63]:
df = pd.read_csv("Costomer+OrderForm.csv")
df.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [64]:
# Select Hypothesis:
# Null hypothsis: H0: mu1 = mu2 = mu3 = mu4
# Alternative hypothsis: H1: Atleast one of them is different.

In [65]:
# Significance 5%
# alpha = 0.05

# Checking value counts in data.

In [67]:
print(df['Phillippines'].value_counts(),'\n',df['Indonesia'].value_counts(),'\n',df['Malta'].value_counts(),'\n',df['India'].value_counts())

Error Free    271
Defective      29
Name: Phillippines, dtype: int64 
 Error Free    267
Defective      33
Name: Indonesia, dtype: int64 
 Error Free    269
Defective      31
Name: Malta, dtype: int64 
 Error Free    280
Defective      20
Name: India, dtype: int64


# Creating Contingency table

In [68]:
contingency_table = [[271,267,269,280],
                    [29,33,31,20]]
print(contingency_table)

[[271, 267, 269, 280], [29, 33, 31, 20]]


# Calculating Expected Values for Observed data

In [69]:
stat, p, df, exp = stats.chi2_contingency(contingency_table)
print("Statistics = ",stat,"\n",'P_Value = ', p,'\n', 'degree of freedom =', df,'\n', 'Expected Values = ', exp)

Statistics =  3.858960685820355 
 P_Value =  0.2771020991233135 
 degree of freedom = 3 
 Expected Values =  [[271.75 271.75 271.75 271.75]
 [ 28.25  28.25  28.25  28.25]]


In [70]:
observed = np.array([271, 267, 269, 280, 29, 33, 31, 20])
expected = np.array([271.75, 271.75, 271.75, 271.75, 28.25, 28.25, 28.25, 28.25])

In [71]:
test_statistic , p_value = stats.chisquare(observed, expected, ddof = df)
print("Test Statistic = ",test_statistic,'\n', 'p_value =',p_value)

Test Statistic =  3.858960685820355 
 p_value = 0.4254298144535761


In [72]:
# Since p_value is greater than alpha_value, 
#so we fail to reject the null hypothesis. 